### ISSUE TITLE
Twitter preview optimize

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/subsquare-landing#20]
#19

**Comment by YoshiyukiSakura** [comment]
# So basically we have got two choices. 
## [Summary Card](https://developer.twitter.com/content/developer-twitter/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image): Title, description, and thumbnail.
## [Summary Card with Large Image](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html): Similar to the Summary Card, but with a prominently-featured image.
<img width="577" alt="image" src="https://user-images.githubusercontent.com/12393771/154020573-50a55309-0cba-4d80-8878-ec459d83cad8.png">

**Comment by Popoulosss** [comment]
file
[subsquare.zip](https://github.com/opensquare-network/subsquare-landing/files/8077819/subsquare.zip)
