### ISSUE TITLE
Design items for interaction and did login

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/subsquare-landing#29]
![a69fdbqSij](https://user-images.githubusercontent.com/2264908/174068844-4fd0aafb-4fd7-43c2-96f2-6879e193676d.jpg)

**Comment by Popoulosss** [comment]
- Implement images of interaction and did login
- Replace images of -1, -2, -3

[Figma link](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=4818%3A37902)

Files
[imgs-features.zip](https://github.com/opensquare-network/subsquare-landing/files/8963486/imgs-features.zip)
