### ISSUE TITLE
Add Litmus to logo press

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare-landing#34]
Files
[litmus.svg.zip](https://github.com/opensquare-network/subsquare-landing/files/9173343/litmus.svg.zip)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/180596326-48439eda-6b80-4ae8-bdae-ad909d1e546a.png">

**Comment by 2nthony** [comment]
- launch app
- slider
- footer logo
