### ISSUE TITLE
report typo

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/subsquare-landing#7]
![image](https://user-images.githubusercontent.com/12393771/151689884-5ed003a0-7278-43fd-8bcc-d48cd19abe9e.png)

**Comment by Popoulosss** [comment]
- [ ] '...PROJECTS'

figma link
https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=3475%3A27922
