### ISSUE TITLE
Image too fuzzy, might change with sharper ones

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/subsquare-landing#8]
# maybe use a 2x png files
![image](https://user-images.githubusercontent.com/12393771/151690049-0eb4df81-016e-4fa9-9be2-a90ce4532471.png)

**Comment by Popoulosss** [comment]
- [ ] Replace images

file
[img-screenshot.zip](https://github.com/opensquare-network/subsquare-landing/files/7965480/img-screenshot.zip)
