### ISSUE TITLE
use a Real copy writing, to replace the placeholder

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/subsquare-landing#9]

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/151690175-de5baea6-7953-4b61-9699-6de460b94f07.png)

**Comment by Popoulosss** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/59445675/153531879-e95c1b82-1f76-4ec6-ac9f-b65df426b9d9.png">

**Comment by Popoulosss** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/59445675/153531909-c82e0e69-d70f-44e2-a7f2-3d5864cb3aab.png">

**Comment by Popoulosss** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/153531939-fd247ce9-20a0-4c4b-b5b0-f1c19e205066.png">
